
name: psijd

services:
  psijd:
    profiles:
      - default
    image: psijd
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psijd
    hostname: psijd
    expose:
      - "5000"
    ports:
      - 10050:5000
    networks:
      - iri-shared
    environment:
      - SLURM_JWT=$SLURM_JWT
    volumes:
      - ./:/opt/psijd
    working_dir: /opt
    command: fastapi dev --host 0.0.0.0 --port 5000 /opt/psijd/service/app.py

  psijd-debug:
    profiles: 
      - debug
    extends: psijd
    container_name: psijd-debug
    expose:
      - "5678"
    ports:
      - 5678:5678
    command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m uvicorn psijd.service.app:app --host 0.0.0.0 --port 5000 --reload

networks:
  iri-shared:
    external: true


