# prometheus-slurm-values.yaml
# Disable node-exporter completely since you only want Slurm pod monitoring
nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    # Target the slurm-exporter specifically
    additionalScrapeConfigs:
    - job_name: 'slurm-exporter'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - slurm
      relabel_configs:
      # Only scrape the slurm-exporter pod
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: slurm-exporter
      # Use port 8080
      - source_labels: [__address__]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?
        replacement: $1:8080
      # Add useful labels
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod_name
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace

    # Limit service and pod monitor discovery to slurm namespace only
    serviceMonitorNamespaceSelector:
      matchLabels:
        name: slurm
    podMonitorNamespaceSelector:
      matchLabels:
        name: slurm
