apiVersion: v1
kind: Service
metadata:
  name: {{ include "psijd.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "psijd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "psijd.selectorLabels" . | nindent 4 }}